name: akshat_portfolio
description: A beautiful portfolio website for Akshat Singh

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  google_fonts: ^6.1.0
  url_launcher: ^6.1.12
  animated_text_kit: ^4.2.2
  visibility_detector: ^0.4.0+2
  code_text_field: ^1.1.0 
  flutter_highlight: ^0.7.0
  highlight: ^0.7.0
  http: ^1.2.1
  flutter_dotenv: ^5.0.2
  provider: ^6.1.5
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/dotenv
    - assets/resume/
